### ISSUE TITLE
[RFC] Separate out Pushes and Comments

### ISSUE THREAD

**Issue by ntalbott** [spreedly/devdigest#2]
Code pushes seem so much more important, and right now it's hard to scan for them vs code pushes. Could we start with a list of pushes, and then rather than individual comments, instead just highlight things that have been commented on, with a list of those who have commented?
- core
  - "Something awesome" pushed by Ryan
  - "Even more awesome since it works" pushed by Duff
  - "What's up with that?" commented on by Nathaniel, Ryan, and Adam

This kind of assumes #1.

**Comment by rwdaigle** [comment]
[Several votes](https://spreedly.slack.com/archives/dev/p1458140800000059) for just having commits be listed, too
